### ISSUE TITLE
reportUploadTask - Curl failed with exit code 22

### ISSUE THREAD

**Issue by SDohle** [cqse/Teamscale-AzureDevOps-Extension#30]
Hi,

I have an issue with the reportUploadTask. I try to upload a trx file. This is the log:

```
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN, server accepted to use http/1.1
* Server certificate:
*  SSL certificate verify result: self signed certificate in certificate chain (19), continuing anyway.
* Server auth using Basic with user 'MyServiceUser'
} [5 bytes data]
> POST /p/MyProject/external-report?format=MS_TEST&revision=... HTTP/1.1
> Host: teamscale.mydomain.net
> Authorization: Basic TOKEN
> User-Agent: curl/7.65.0
> Accept: */*
> Content-Length: 70582
> Content-Type: multipart/form-data; boundary=------------------------6a0ca3f389ac23d4
> Expect: 100-continue
> 
{ [5 bytes data]
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
{ [57 bytes data]
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
{ [57 bytes data]
* old SSL session ID is stale, removing
{ [5 bytes data]
* Mark bundle as not supporting multiuse
< HTTP/1.1 100 Continue
} [5 bytes data]
* Mark bundle as not supporting multiuse
* The requested URL returned error: 404 Not Found

 92 70582    0     0   92 65536      0   820k --:--:-- --:--:-- --:--:--  820k
* Closing connection 0
} [5 bytes data]
curl: (22) The requested URL returned error: 404 Not Found
##[error]Task failed. Please check the log for further details.
Error: The process '_work\_tasks\TeamscaleReportUploader_fa6beede-4fe1-11e9-8d71-071835da2614\1.2.5\curl\windows\curl.exe' failed with exit code 22
    at ExecState._setResult (_work\_tasks\TeamscaleReportUploader_fa6beede-4fe1-11e9-8d71-071835da2614\1.2.5\node_modules\azure-pipelines-task-lib\toolrunner.js:931:25)
    at ExecState.CheckComplete (_work\_tasks\TeamscaleReportUploader_fa6beede-4fe1-11e9-8d71-071835da2614\1.2.5\node_modules\azure-pipelines-task-lib\toolrunner.js:914:18)
    at ChildProcess.<anonymous> (_work\_tasks\TeamscaleReportUploader_fa6beede-4fe1-11e9-8d71-071835da2614\1.2.5\node_modules\azure-pipelines-task-lib\toolrunner.js:827:19)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:920:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:230:5)
##[error]Upload to Teamscale failed with error: The process '_work\_tasks\TeamscaleReportUploader_fa6beede-4fe1-11e9-8d71-071835da2614\1.2.5\curl\windows\curl.exe' failed with exit code 22
Finishing: Upload **/*.trx to Teamscale https://teamscale.mydomain.net
```

We are using:
- TeamScale 6.5 
- AzureDevops Server 2020
- TeamScale Extension 1.2.7
- Agent OS: Windows

Is this the right place? Or shoul I open a support ticket?

Best regards
Steffen

**Comment by Macariel** [comment]
Hi Steffen,

I would suggest writing support@cqse.eu.
In this case I am not sure what the reason is for the 404 and would need more specific information, which is probably better exchanged via e-mail than this public forum.

If you are going to do that, could you also attach a support-request from the Teamscale instance to which you are trying to upload the reports to?

Best regards,
Timo

**Comment by SDohle** [comment]
Ok,
problem is solved. I didn't expected the project_id field to be case sensitive.
My project name is 'MyProject_APIs', the project id is 'myproject_apis' and I used 'MyProject_APIs' in the task properties.
I just switched to  'myproject_apis' and it"s working now.

Thanks & best regards
Steffen
